<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UNDP Summary Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1f2937;
            font-size: 12px;
        }
        h1 {
            font-size: 20px;
            margin-bottom: 10px;
            color: #0f172a;
        }
        h2 {
            font-size: 15px;
            margin-top: 18px;
            margin-bottom: 8px;
            color: #1e293b;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #d1d5db;
            padding: 6px;
            text-align: left;
        }
        th {
            background: #f3f4f6;
        }
        .meta {
            margin-bottom: 12px;
            color: #475569;
        }
    </style>
</head>
<body>
<h1>RASD Platform Summary Report</h1>

<div class="meta">
    <div>Generated at: {{ $generatedAt->toDateTimeString() }}</div>
    <div>Generated by: {{ $generatedBy->name }} ({{ $generatedBy->role }})</div>
</div>

<h2>Filters</h2>
<table>
    <thead>
    <tr>
        <th>Filter</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    @foreach($filters as $key => $value)
        <tr>
            <td>{{ $key }}</td>
            <td>{{ is_scalar($value) ? $value : json_encode($value) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<h2>KPI Summary</h2>
<table>
    <thead>
    <tr>
        <th>Metric</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    @foreach($summary as $key => $value)
        <tr>
            <td>{{ str_replace('_', ' ', ucfirst($key)) }}</td>
            <td>{{ $value }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<h2>Status Breakdown</h2>
<table>
    <thead>
    <tr>
        <th>Status</th>
        <th>Count</th>
    </tr>
    </thead>
    <tbody>
    @foreach($statusBreakdown as $status => $count)
        <tr>
            <td>{{ str_replace('_', ' ', ucfirst($status)) }}</td>
            <td>{{ $count }}</td>
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>
